kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: demo-dev
  labels:
    app: {{ template "k8sadmin.name" . }}
    chart: {{ template "k8sadmin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
