---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: demo-to-demo-admin
  labels:
    app: {{ template "k8sadmin.name" . }}
    chart: {{ template "k8sadmin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-dev
subjects:
- kind: Group
  name: demo-group
  apiGroup: rbac.authorization.k8s.io
